### ISSUE TITLE
Hard to reproduce error on docker

### ISSUE THREAD

**Issue by Mik1ll** [Mik1ll/LuaRenamer#9]
Two users, Eclipse and kero_chan reported this error when renaming files.
```
17:50:20| SVR_VideoLocal_Place --- System.InvalidCastException: Unable to cast object of type 'NLua.LuaUserData' to type 'KeraLua.LuaFunction'.
   at NLua.Lua.GetFunction(String fullPath)
   at NLua.Lua.RegisterFunction(String path, Object target, MethodBase function)
   at LuaRenamer.LuaRenamer.CreateLuaEnv()
   at LuaRenamer.LuaRenamer.RunSandboxed(String code)
   at LuaRenamer.LuaRenamer.GetInfo()
   at LuaRenamer.LuaRenamer.GetFilename(RenameEventArgs args)
   at Shoko.Server.RenameFileHelper.GetFilename(SVR_VideoLocal_Place place, String scriptName) in /usr/src/app/source/Shoko.Server/Renamer/RenameFileHelper.cs:line 69
```
```
08:39:38| --- Trying to load /home/shoko/.shoko/Shoko.CLI/plugins/LuaRenamer/KeraLua.dll
Process terminated. A callback was made on a garbage collected delegate of type 'KeraLua!KeraLua.LuaFunction::Invoke'.
   at KeraLua.NativeMethods.lua_settable(IntPtr, Int32)
08:40:56| --- Trying to load /home/shoko/.shoko/Shoko.CLI/plugins/LuaRenamer/KeraLua.dll
            *Error: Unable to cast object of type 'NLua.LuaUserData' to type 'KeraLua.LuaFunction'.
            *Error: Unable to cast object of type 'NLua.LuaUserData' to type 'KeraLua.LuaFunction'.
            *Error: Unable to cast object of type 'NLua.LuaTable' to type 'KeraLua.LuaFunction'.
            *Error: Unable to cast object of type 'NLua.LuaUserData' to type 'KeraLua.LuaFunction'.
08:58:45| --- Trying to load /home/shoko/.shoko/Shoko.CLI/plugins/LuaRenamer/KeraLua.dll
```

**Comment by Mik1ll** [comment]
May have been fixed with [v1.1.0](https://github.com/Mik1ll/LuaRenamer/releases/tag/v1.1.0).
Has not been reported for a while, closing.
